title: "ROCKITPLAY"
stackDescription: "ROCKITPLAY Instance (Engine + Edge)"
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

groupings:

  - title: "Predefined General Configuration"
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - current_user_ocid
      - region
      - rockit_engine_link_b64
      - VERSION
      - ENGINE_SRC_HASH
      - EDGE_SRC_HASH
      - MC_HASH

  - title: "ROCKITPLAY Instance"
    visible: true
    variables:
      - dacslabs_link_b64
      - rockit_base_link_b64
      - env_label
      - WORKSPACE

  - title: "Maintenance"
    visible: true
    variables:
      - MAINTENANCE_MODE

  - title: "Advanced Settings"
    visible: true
    variables:
      - show_advanced_settings
      - RSI_URL
      - runtime
      - CWL_CONTAINER_SHAPE
      - N_CONTAINER_INSTANCES

  - title: "MongoDB Atlas Integration"
    visible:
      and:
        - eq:
            - ${env_label}
            - "prod: Production or Live Environment"
    variables:
      - PROD_MONGODBATLAS_DB_TYPE
      - PROD_MONGODBATLAS_REGION_CLUSTER
      - PROD_MONGODBATLAS_CLUSTER_SIZE
      - MONGODBATLAS_IP_ACCESS_LIST

  - title: "MongoDB Atlas Integration"
    visible:
      and:
        - eq:
            - ${env_label}
            - "stage: Staging Environment"
    variables:
      - STAGE_MONGODBATLAS_DB_TYPE
      - STAGE_MONGODBATLAS_REGION_CLUSTER
      - STAGE_MONGODBATLAS_CLUSTER_SIZE
      - MONGODBATLAS_IP_ACCESS_LIST

  - title: "MongoDB Atlas Integration"
    visible:
      and:
        - eq:
            - ${env_label}
            - "test: Testing Environment"
    variables:
      - TEST_MONGODBATLAS_DB_TYPE
      - TEST_MONGODBATLAS_REGION_CLUSTER
      - TEST_MONGODBATLAS_CLUSTER_SIZE
      - MONGODBATLAS_IP_ACCESS_LIST


  - title: "Slack Integration"
    visible:
      or:
        - eq:
          - ${env_label}
          - "prod: Production or Live Environment"
        - eq:
          - ${env_label}
          - "stage: Staging Environment"
        - eq:
          - ${env_label}
          - "test: Testing Environment"
    variables:
      - ENGINE_SLACK_ADMIN_CHANNEL
      - EDGE_SLACK_ADMIN_CHANNEL

  - title: "SMTP Configuration"
    visible: true
    variables:
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD

variables:

  dacslabs_link_b64:
    type: string
    title: "DACSLABS Link"
    description: "Please paste the dacslabs_link provided by DACSLABS."
    visible: true
    required: true
    pattern: "^dacslabslnk1.[-A-Za-z0-9+/]*={0,3}$"

  rockit_base_link_b64:
    type: string
    title: "ROCKIT Base Link"
    description: "ROCKITPLAY requires the ROCKIT Base Environment Stack to be configured and
                  installed. Please copy the 'rockit_base_link' value from the latest successful
                  'Apply' job of the OCI Stack 'ROCKIT Base Environment'."
    visible: true
    required: true
    pattern: "^dxbaselnk1.[-A-Za-z0-9+/]*={0,3}$"

  env_label:
    type: enum
    title: "Instance Environment"
    description: "Please specify the instance environment.
                  (1) 'prod':  Deploys production-grade resources which involve additional
                               costs such as: (a) provisioned concurrency units to speed up
                               initial lambda function invocation and (b) MongoDB Atlas
                               Serverless instance.
                  (2) 'stage': Typically close to the production environment but limited
                               with respect to storage and performance as
                               low-pricing / free tier resources are allocated.
                  (3) 'test':  Add debug and side-loading functionalities, deploys
                               low-pricing / free tier components. Operations are limited
                               with respect to storage size and performance."
    required: true
    enum:
      - "prod: Production or Live Environment"
      - "stage: Staging Environment"
      - "test: Testing Environment"

  WORKSPACE:
    type: string
    title: "Instance Identifier"
    description: "Please provide an identifier which will be used as suffix to all
                  resources belonging to this ROCKITPLAY instance.
                  If you plan to deploy a production system only simply use 'prod' or 'live'"
    required: true
    pattern: "^[a-z][a-z0-9]{1,18}$"


  MAINTENANCE_MODE:
    type: boolean
    title: "Maintenance Mode"
    description: "Enable maintenance mode for the ROCKIT Edge instance?
                  This will disable all API endpoints and periodic jobs."
    visible: true
    default: false


  show_advanced_settings:
    type: boolean
    title: "Show Advanced Settings"
    description: "Override advanced configuration. If unsure, keep unchecked."
    visible: true
    default: false

  RSI_URL:
    type: string
    title: "ROCKIT StreamInstaller URL"
    description: "Define the URL to download rsi.exe"
    default: "https://public.cloud.rockitplay.com/rsi"
    required: true
    visible: ${show_advanced_settings}

  runtime:
    type: enum
    title: "HTTP Request Runtime"
    description: "Please specify which runtime environment should be used
                  to handle HTTP requests.
                  (1) 'containers':  Configure container workloads for production environments.
                                     Containers are running continuously and provide
                                     low-latency responses but involve additional costs.
                  (2) 'functions':   Use serverless functions to handle HTTP requests.
                                     Functions are cost-efficient as you only pay for
                                     actual usage but may introduce latency during cold starts."
    visible: ${show_advanced_settings}
    required: true
    enum:
      - "containers"
      - "functions"

  CWL_CONTAINER_SHAPE:
    type: enum
    title: "Container Shape for ROCKITPLAY instance"
    description: "Please choose the shape to use for container instances."
    visible:
      and:
        - ${show_advanced_settings}
        - eq:
          - ${runtime}
          - "containers"
    required: true
    default: "CI.Standard.E4.Flex"
    enum:
      - "CI.Standard.E4.Flex"
      - "CI.Standard.A1.Flex"

  N_CONTAINER_INSTANCES:
    type: number
    title: "Number of container instances for ROCKITPLAY"
    description: "Please enter the number of simultaneously running container
                  instances."
    visible:
      and:
        - ${show_advanced_settings}
        - eq:
          - ${runtime}
          - "containers"
    required: true
    minimum: 1
    default: 1

  # --- mongodb PROD
  PROD_MONGODBATLAS_DB_TYPE:
    type: enum
    title: "MongoDB Atlas Cluster Type"
    description: "Please choose the type of the MongoDB Atlas cluster."
    required: true
    visible:
      and:
        - eq:
            - ${env_label}
            - "prod: Production or Live Environment"
    default: "advanced_cluster: Advanced Cluster for production environments"
    enum:
      - "free_cluster: Free Tier Cluster"
      - "advanced_cluster: Advanced Cluster for production environments"

  PROD_MONGODBATLAS_REGION_CLUSTER:
    type: enum
    title: "MongoDB Atlas Cluster Region"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    required: true
    visible:
      and:
        - eq:
            - ${env_label}
            - "prod: Production or Live Environment"
    enum:
      - "AF_SOUTH_1: Cape Town, South Africa"
      - "AP_EAST_1: Hong Kong, China"
      - "AP_NORTHEAST_1: Tokyo, Japan"
      - "AP_NORTHEAST_2: Seoul, South Korea"
      - "AP_SOUTHEAST_1: Singapore"
      - "AP_SOUTHEAST_2: Sydney, NSW, Australia"
      - "AP_SOUTH_1: Mumbai, India"
      - "EU_CENTRAL_1: Frankfurt, Germany"
      - "EU_NORTH_1: Stockholm, Sweden"
      - "EU_SOUTH_1: Milan, Italy"
      - "EU_SOUTH_2: Spain"
      - "EU_WEST_1: Ireland"
      - "EU_WEST_3: Paris, France"
      - "IL_CENTRAL_1: Tel Aviv, Israel"
      - "ME_SOUTH_1: Bahrain"
      - "SA_EAST_1: Sao Paulo, Brazil"
      - "US_EAST_1: Northern Virginia, USA"
      - "US_WEST_2: Oregon, USA"

  PROD_MONGODBATLAS_CLUSTER_SIZE:
    type: string
    title: "MongoDB Atlas Cluster Instance Size"
    visible:
      and:
        - eq:
            - ${env_label}
            - "prod: Production or Live Environment"
        - eq:
            - ${PROD_MONGODBATLAS_DB_TYPE}
            - "advanced_cluster: Advanced Cluster for production environments"

  # --- mongodb STAGE
  STAGE_MONGODBATLAS_DB_TYPE:
    type: enum
    title: "MongoDB Atlas Cluster Type"
    description: "Please choose the type of the MongoDB Atlas cluster."
    required: true
    visible:
      and:
        - eq:
            - ${env_label}
            - "stage: Staging Environment"
    default: "advanced_cluster: Advanced Cluster for production environments"
    enum:
      - "free_cluster: Free Tier Cluster"
      - "advanced_cluster: Advanced Cluster for production environments"

  STAGE_MONGODBATLAS_REGION_CLUSTER:
    type: enum
    title: "MongoDB Atlas Cluster Region"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    required: true
    visible:
      and:
        - eq:
            - ${env_label}
            - "stage: Staging Environment"
    enum:
      - "AF_SOUTH_1: Cape Town, South Africa"
      - "AP_EAST_1: Hong Kong, China"
      - "AP_NORTHEAST_1: Tokyo, Japan"
      - "AP_NORTHEAST_2: Seoul, South Korea"
      - "AP_SOUTHEAST_1: Singapore"
      - "AP_SOUTHEAST_2: Sydney, NSW, Australia"
      - "AP_SOUTH_1: Mumbai, India"
      - "EU_CENTRAL_1: Frankfurt, Germany"
      - "EU_NORTH_1: Stockholm, Sweden"
      - "EU_SOUTH_1: Milan, Italy"
      - "EU_SOUTH_2: Spain"
      - "EU_WEST_1: Ireland"
      - "EU_WEST_3: Paris, France"
      - "IL_CENTRAL_1: Tel Aviv, Israel"
      - "ME_SOUTH_1: Bahrain"
      - "SA_EAST_1: Sao Paulo, Brazil"
      - "US_EAST_1: Northern Virginia, USA"
      - "US_WEST_2: Oregon, USA"

  STAGE_MONGODBATLAS_CLUSTER_SIZE:
    type: string
    title: "MongoDB Atlas Cluster Instance Size"
    visible:
      and:
        - eq:
            - ${env_label}
            - "stage: Staging Environment"
        - eq:
            - ${STAGE_MONGODBATLAS_DB_TYPE}
            - "advanced_cluster: Advanced Cluster for production environments"

  # --- mongodb TEST
  TEST_MONGODBATLAS_DB_TYPE:
    type: enum
    title: "MongoDB Atlas Cluster Type"
    description: "Please choose the type of the MongoDB Atlas cluster."
    required: true
    visible:
      and:
        - eq:
            - ${env_label}
            - "test: Testing Environment"
    default: "free_cluster: Free Tier Cluster"
    enum:
      - "free_cluster: Free Tier Cluster"
      - "advanced_cluster: Advanced Cluster for production environments"

  TEST_MONGODBATLAS_REGION_CLUSTER:
    type: enum
    title: "MongoDB Atlas Cluster Region"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    required: true
    visible:
      and:
        - eq:
            - ${env_label}
            - "test: Testing Environment"
    enum:
      - "AF_SOUTH_1: Cape Town, South Africa"
      - "AP_EAST_1: Hong Kong, China"
      - "AP_NORTHEAST_1: Tokyo, Japan"
      - "AP_NORTHEAST_2: Seoul, South Korea"
      - "AP_SOUTHEAST_1: Singapore"
      - "AP_SOUTHEAST_2: Sydney, NSW, Australia"
      - "AP_SOUTH_1: Mumbai, India"
      - "EU_CENTRAL_1: Frankfurt, Germany"
      - "EU_NORTH_1: Stockholm, Sweden"
      - "EU_SOUTH_1: Milan, Italy"
      - "EU_SOUTH_2: Spain"
      - "EU_WEST_1: Ireland"
      - "EU_WEST_3: Paris, France"
      - "IL_CENTRAL_1: Tel Aviv, Israel"
      - "ME_SOUTH_1: Bahrain"
      - "SA_EAST_1: Sao Paulo, Brazil"
      - "US_EAST_1: Northern Virginia, USA"
      - "US_WEST_2: Oregon, USA"

  TEST_MONGODBATLAS_CLUSTER_SIZE:
    type: string
    title: "MongoDB Atlas Cluster Instance Size"
    visible:
      and:
        - eq:
            - ${env_label}
            - "test: Testing Environment"
        - eq:
            - ${TEST_MONGODBATLAS_DB_TYPE}
            - "advanced_cluster: Advanced Cluster for production environments"

  MONGODBATLAS_IP_ACCESS_LIST:
    type: string
    title: "MongoDB IP Access List"
    description: "Please enter a comma separated list of CIDR address notations
                  or leave empty for no additional access."
    required: false


  # --- EMail integration
  SMTP_HOST:
    type: string
    title: "SMTP Host"
    description: "ROCKITPLAY sends automatic emails, e.g., user invitations, password
                  resets etc. Please enter the hostname of your SMTP server."
    required: true
    visible: true

  SMTP_PORT:
    type: number
    title: "SMTP Port"
    description: "Please enter the port of your SMTP server."
    required: true
    default: 587
    visible: true
    minimum: 1
    maximum: 65535

  SMTP_USER:
    type: string
    title: "SMTP User"
    description: "Please enter the user name to authenticate against your SMTP server."
    required: true
    visible: true

  SMTP_PASSWORD:
    type: string
    title: "SMTP Password"
    description: "Please enter the password to authenticate against your SMTP server."
    required: true
    visible: true
    sensitive: true
    minLength: 8

  # --- Slack integration
  ENGINE_SLACK_ADMIN_CHANNEL:
    type: string
    title: "Slack Admin Channel for ROCKIT Engine"
    description: "Please enter the Id of the Slack channel which should receive
                  notifications for the site administrator, e.g, '#my-admin-channel'"
    required: true

  EDGE_SLACK_ADMIN_CHANNEL:
    type: string
    title: "Slack Admin Channel for ROCKIT Edge"
    description: "Please enter the Id of the Slack channel which should receive
                  notifications for the site administrator, e.g, '#my-admin-channel'"
    required: true