title: "ROCKITPLAY"
stackDescription: "ROCKITPLAY Instance (Engine + Edge)"
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

groupings:

  - title: "Predefined General Configuration"
    visible: false
    variables:
    - tenancy_ocid
    - compartment_ocid
    - current_user_ocid
    - region
    - rockit_engine_link_b64
    - VERSION
    - MONGODBATLAS_CLUSTER_SIZE
    - ENGINE_LB_BANDWIDTH_MBPS

  - title: "ROCKITPLAY Instance"
    visible: true
    variables:
    - dacslabs_link_b64
    - rockit_base_link_b64
    - env_label
    - WORKSPACE
    - MAINTENANCE_MODE

  - title: "Advanced Settings"
    visible: true
    variables:
      - show_advanced_settings
      - RSI_URL
      - use_cwl
      - CWL_CONTAINER_SHAPE
      - N_CONTAINER_INSTANCES
      - EDGE_LB_BANDWIDTH_MBPS


  - title: "MongoDB Atlas Integration"
    visible: true
    variables:
      - EDGE_MONGODBATLAS_DB_TYPE
      - EDGE_MONGODBATLAS_REGION_CLUSTER
      - ENGINE_MONGODBATLAS_DB_TYPE
      - ENGINE_MONGODBATLAS_REGION_CLUSTER

  - title: "Slack Integration"
    visible:
      or:
        - eq:
          - ${env_label}
          - "prod: Production or Live Environment"
        - eq:
          - ${env_label}
          - "stage: Staging Environent"
        - eq:
          - ${env_label}
          - "test: Testing Environment"
    variables:
    - ENGINE_SLACK_ADMIN_CHANNEL
    - ENGINE_SLACK_ERROR_CHANNEL
    - ENGINE_SLACK_INFO_CHANNEL
    - EDGE_SLACK_ADMIN_CHANNEL
    - EDGE_SLACK_ERROR_CHANNEL
    - EDGE_SLACK_INFO_CHANNEL

variables:

  dacslabs_link_b64:
    type: string
    title: "DACSLABS Link"
    description: "Please copy the dacslabs_link provided by DACSLABS."
    visible: true
    required: true
    pattern: "^dacslabslnk1.[-A-Za-z0-9+/]*={0,3}$"

  rockit_base_link_b64:
    type: string
    title: "ROCKIT Base Link"
    description: "ROCKITPLAY requires the ROCKIT Base Environment Stack to be configured and
                  installed. Please copy the 'rockit_base_link' value from the latest successul
                  job of the OCI Stack 'ROCKIT Base Environment'."
    visible: true
    required: true
    pattern: "^dxbaselnk1.[-A-Za-z0-9+/]*={0,3}$"

  env_label:
    type: enum
    title: "Instance Environment"
    description: "Please specify the instance environment.
                  (1) 'prod':  Deploys production-grade resources which involve additional
                               costs such as: (a) provisioned concurrency units to speed up
                               initial lambda function invocation and (b) MongoDB Atlas
                               Serverless instance.
                  (2) 'stage': Typically close to the production environment but limited
                               with respect to storage and performance as
                               low-pricing / free tier resources are allocated.
                  (3) 'test':  Add debug and side-loading functionalities, deploys
                               low-pricing / free tier components. Operations are limited
                               with respect to storage size and performance."
    enum:
    - "prod: Production or Live Environment"
    - "stage: Staging Environent"
    - "test: Testing Environment"

  WORKSPACE:
    type: string
    title: "Instance Identifier"
    description: "Please provide an identifier which will be used as suffix to all
                  resources belonging to this ROCKIT Engine instance.
                  If you plan to deploy a production system only simply use 'prod' or 'live'"
    required: true
    pattern: "^[a-z][a-z0-9]{1,19}$"

  MAINTENANCE_MODE:
    type: boolean
    title: "Maintenance Mode"
    description: "Enable maintenance mode for the ROCKIT Edge instance?
                  This will disable all API endpoints and periodic jobs."
    visible: true
    default: false

  show_advanced_settings:
    type: boolean
    title: "Show Advanced Settings"
    description: "Override advanced configuration. If unsure, keep unchecked."
    visible: true

  RSI_URL:
    type: string
    title: "ROCKIT StreamInstaller URL"
    description: "Define the URL to download rsi.exe"
    default: "https:/public.cloud.rockitplay.com/rsi"
    required: true
    visible: ${show_advanced_settings}

  use_cwl:
    type: boolean
    title: "Use Container Workloads"
    description: "Use container workloads instead of lambda functions to handle
                  API requests? Before enabling make sure you understand the cost
                  structure of container workloads. If unsure, keep unchecked."
    visible: ${show_advanced_settings}
    default:
      or:
      - eq:
        - ${env_label}
        - "prod: Production or Live Environment"
      - eq:
        - ${env_label}
        - "stage: Staging Environent"

  CWL_CONTAINER_SHAPE:
    type: enum
    title: "Container Shape"
    description: "Please choose the shape of the container instances."
    visible: ${use_cwl}
    required: true
    default: "CI.Standard.A1.Flex"
    enum:
    - "CI.Standard.A1.Flex"
    - "CI.Standard.E4.Flex"

  N_CONTAINER_INSTANCES:
    type: number
    title: "Number of container instances"
    description: "Please enter the number of simultaneously running container
                  instances."
    visible:
      and:
      - ${show_advanced_settings}
      - ${use_cwl}
    required: true
    minimum: 1
    default: 1

  EDGE_LB_BANDWIDTH_MBPS:
    type: number
    title: "Load Balancer Bandwidth for ROCKIT Edge"
    description: "Please enter the bandwidth of the load balancer in Mbps."
    visible: ${use_cwl}
    required: true
    default: 10
    minimum: 10
    maximum: 8000

  EDGE_MONGODBATLAS_DB_TYPE:
    type: enum
    title: "MongoDB Atlas Cluster Type for ROCKIT Edge"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters
                  taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    default: "free_cluster"
    required: true
    visible:  true
    enum:
    - "free_cluster"
    - "advanced_cluster"

  EDGE_MONGODBATLAS_REGION_CLUSTER:
    type: enum
    title: "MongoDB Atlas Cluster Region for ROCKIT Edge"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    required: true
    visible:
      or:
        - eq:
          - ${env_label}
          - "prod: Production or Live Environment"
        - eq:
          - ${env_label}
          - "stage: Staging Environent"
        - eq:
          - ${env_label}
          - "test: Testing Environment"
    enum:
    - "AF_SOUTH_1: Cape Town, South Africa"
    - "AP_EAST_1: Hong Kong, China"
    - "AP_NORTHEAST_1: Tokyo, Japan"
    - "AP_NORTHEAST_2: Seoul, South Korea"
    - "AP_SOUTHEAST_1: Singapore"
    - "AP_SOUTHEAST_2: Sydney, NSW, Australia"
    - "AP_SOUTH_1: Mumbai, India"
    - "EU_CENTRAL_1: Frankfurt, Germany"
    - "EU_NORTH_1: Stockholm, Sweden"
    - "EU_SOUTH_1: Milan, Italy"
    - "EU_SOUTH_2: Spain"
    - "EU_WEST_1: Ireland"
    - "EU_WEST_3: Paris, France"
    - "IL_CENTRAL_1: Tel Aviv, Israel"
    - "ME_SOUTH_1: Bahrain"
    - "SA_EAST_1: Sao Paulo, Brazil"
    - "US_EAST_1: Northern Virginia, USA"
    - "US_WEST_2: Oregon, USA"

  ENGINE_MONGODBATLAS_DB_TYPE:
    type: enum
    title: "MongoDB Atlas Cluster Type for ROCKIT Engine"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters
                  taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    default: "free_cluster"
    required: true
    visible:  true
    enum:
    - "free_cluster"
    - "advanced_cluster"

  ENGINE_MONGODBATLAS_REGION_CLUSTER:
    type: enum
    title: "MongoDB Atlas Cluster Region for ROCKIT Engine"
    description: "Please choose the location of the MongoDB Atlas instances.
                  Location identifiers supporting M0 and M10+ clusters taken from
                  https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws-availability-zones"
    required: true
    visible:
      or:
        - eq:
          - ${env_label}
          - "prod: Production or Live Environment"
        - eq:
          - ${env_label}
          - "stage: Staging Environent"
        - eq:
          - ${env_label}
          - "test: Testing Environment"
    enum:
    - "AF_SOUTH_1: Cape Town, South Africa"
    - "AP_EAST_1: Hong Kong, China"
    - "AP_NORTHEAST_1: Tokyo, Japan"
    - "AP_NORTHEAST_2: Seoul, South Korea"
    - "AP_SOUTHEAST_1: Singapore"
    - "AP_SOUTHEAST_2: Sydney, NSW, Australia"
    - "AP_SOUTH_1: Mumbai, India"
    - "EU_CENTRAL_1: Frankfurt, Germany"
    - "EU_NORTH_1: Stockholm, Sweden"
    - "EU_SOUTH_1: Milan, Italy"
    - "EU_SOUTH_2: Spain"
    - "EU_WEST_1: Ireland"
    - "EU_WEST_3: Paris, France"
    - "IL_CENTRAL_1: Tel Aviv, Israel"
    - "ME_SOUTH_1: Bahrain"
    - "SA_EAST_1: Sao Paulo, Brazil"
    - "US_EAST_1: Northern Virginia, USA"
    - "US_WEST_2: Oregon, USA"


  ENGINE_SLACK_ADMIN_CHANNEL:
    type: string
    title: "Slack Channel for ROCKIT Engine Site-Admins"
    description: "Please enter the Id of the Slack channel which should receive
                  notifications for the site administrators of ROCKIT Engine, e.g,
                  '#my-admin-channel'"
    required: true

  ENGINE_SLACK_ERROR_CHANNEL:
    type: string
    title: "Slack Channel for ROCKIT Engine Errors"
    description: "Please enter the Id of the Slack channel which should receive
                  error notifications from ROCKIT Engine, e.g, '#my-error-channel'"
    required: true

  ENGINE_SLACK_INFO_CHANNEL:
    type: string
    title: "Slack Channel for ROCKIT Engine Infos"
    description: "Please enter the Id of the Slack channel which should receive
                  information notifications from ROCKIT Engine, e.g., '#my-info-channel'"
    required: true

  EDGE_SLACK_ADMIN_CHANNEL:
    type: string
    title: "Slack Channel for ROCKIT Edge Site-Admins"
    description: "Please enter the Id of the Slack channel which should receive
                  notifications for the site administrators of ROCKIT Edge, e.g,
                  '#my-admin-channel'"
    required: true

  EDGE_SLACK_ERROR_CHANNEL:
    type: string
    title: "Slack Channel for ROCKIT Edge Errors"
    description: "Please enter the Id of the Slack channel which should receive
                  error notifications from ROCKIT Edge, e.g, '#my-error-channel'"
    required: true

  EDGE_SLACK_INFO_CHANNEL:
    type: string
    title: "Slack Channel for ROCKIT Edge Infos"
    description: "Please enter the Id of the Slack channel which should receive
                  information notifications from ROCKIT Edge, e.g., '#my-info-channel'"
    required: true